### ISSUE TITLE
Generate Pukey is Blank

### ISSUE THREAD

**Issue by canedmonkey** [ribbons/TaskerRsync#229] opened 2024-09-08 13:29 UTC
Hi,

I have a Task which runs Generate Private Key (2048,RSA,True), then get Get Public Key and finally Write File which writes %pubkey to file.

The Task runs without error but the file contains no key, only '%pubkey' which suggests the variable is empty.

Without an error, I have no way of knowing what's going wrong. Is there another way I can check what values are being generated in the Generate/Get actions?

Thanks

**Comment by ribbons** [comment] 2024-09-09 11:57
There isn't any more information returned about what the steps have generated but (at least in theory) if anything does go wrong during the private key generation or fetching the public key from it, both should return errors.

If you look at the device logs with logcat (via adb), there are messages written before or after running dropbearkey each time which might provide extra clues if there is a bug, otherwise I'd double check the file output task and maybe get the output from some other means to rule that step out of the equation.

**Comment by StupidNamez** [comment] 2024-09-19 09:28
Hi, sorry for the delay. You can close this. It was a much wider issue caused by my s9 and lineageos not getting on together. Thanks for your help.

**Comment by ribbons** [comment] 2024-09-19 10:52
Okay, no worries - cheers for the update :+1:

**Closed by ribbons** 2024-09-19 10:52 UTC
Labels: needinfo
