### ISSUE TITLE
Error when running Rsync

### ISSUE THREAD

**Issue by StupidNamez** [ribbons/TaskerRsync#78] opened 2022-11-17 16:04 UTC
Using Rsync for Tasker 0.9 

I have key set up successfully on target server but I get this error when trying to run rsync:

15.45.09/E FIRE PLUGIN: rsync / com.twofortyfouram.locale.intent.action.FIRE_SETTING: 6 bundle keys
15.45.09/E rsync: plugin comp: com.nerdoftheherd.tasker.rsync/com.joaomgcd.taskerpluginlibrary.action.IntentServiceAction
15.45.09/E add wait type Plugin1 time 60
15.45.09/E add wait type Plugin1 done
15.45.09/E handlePluginFinish: taskExeID: 1 result 3
15.45.09/E pending result code
15.45.09/E add wait task
15.45.43/E Error: 2
15.45.43/E WARNING: Ignoring unknown option -4

ssh: Connection to user@192.168.1.10:22 exited: Connect failed: Software caused connection abort
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(231) [sender=v3.2.6]

**Comment by ribbons** [comment] 2022-11-17 17:05
If there isn't anything illuminating in the SSH server logs (that's usually where the information about why it isn't allowing the connection is written), I'd suggest trying the dbclient action with arguments something like:
```
-vvv user@192.168.1.10 true
```

That should generally result in a fair amount of output and generally a pointer in the right direction - let me know how you get on.

**Comment by ribbons** [comment] 2022-11-18 16:34
Curious, adding `-vvv` works for me for the dbclient action with Rsync for Tasker 0.9.  I can understand that happening if you had version 0.8 installed rather than 0.9 as the bundled version of dbclient didn't have trace enabled.  Could you check the version you have installed?

**Comment by StupidNamez** [comment] 2022-11-21 13:51
Sorry, my misttake. I was on version 0.8. I must have downloaded it just before you posted the new version as I thought I was on newest release. Now Upgraded to 0.9 and this is what I now get with dbclient action:

`
13.30.51/E FIRE PLUGIN: dbclient / com.twofortyfouram.locale.intent.action.FIRE_SETTING: 7 bundle keys
13.30.51/E dbclient: plugin comp: com.nerdoftheherd.tasker.rsync/com.joaomgcd.taskerpluginlibrary.action.IntentServiceAction
13.30.51/E add wait type Plugin1 time 60
13.30.51/E add wait type Plugin1 done
13.30.51/E handlePluginFinish: taskExeID: 1 result 3
13.30.51/E pending result code
13.30.51/E add wait task
13.31.51/E Error: null
`

**Comment by ribbons** [comment] 2022-11-21 19:16
How strange!  If I run that command against a server that doesn't let me connect, I get output that matches up until your `Error: null` line - instead of that I get an error code and then loads of lines of trace following it.

What version of Android are you running and what's the device?

**Comment by StupidNamez** [comment] 2022-11-22 10:57
I'm using a Galaxy S9 running LineageOS 18 (Android 11). The server is running Open Media Vault 6.

I've managed to get other Rsync apps to work on this device and connect to my server.. I cant remember exactly which app it was but it worked flawlessly only it used password authentication (which I've now disabled on the server) and did not integrate with Tasker.

**Comment by ribbons** [comment] 2022-11-22 18:59
> I'm using a Galaxy S9 running LineageOS 18 (Android 11). The server is running Open Media Vault 6.

Okay, great - so nothing unusual then :+1:, I'm running it under LineageOS 19 (but was running it under 18 before I upgraded).

I'm a little bit baffled really, any chance you could see what shows up in logcat at the point that the plugin is run?  With a bit of luck there will be a relevant error message or stack trace there that might explain the missing trace output.

**Comment by ribbons** [comment] 2022-12-05 17:58
I'm going to go ahead and close this now as I can't reproduce it at my end and would need some more info to be able to understand the problem.

**Closed by ribbons** 2022-12-05 17:58 UTC
Labels: needinfo
